### ISSUE TITLE
Error when generating dictionaries.

### ISSUE THREAD

**Issue by reysu** [gkovacs/cantodict-kindle-mobi#1]
Hi, when I run the code `python3 mkdict.py > dictionary.txt` I get a TypeError. This is what it says: 
`Traceback (most recent call last):
  File "mkdict.py", line 677, in <module>
    main()
  File "mkdict.py", line 673, in main
    for line in make_stardict_lines():
  File "mkdict.py", line 601, in make_stardict_lines
    for item in get_stardict_items():
TypeError: memoize() missing 1 required positional argument: 'f'`

I have all the requirements installed.

**Comment by ngokchaoho** [comment]
I forked and made some adjustment and tested on MacOS Catalina. I removed memoize dependencies by defining my own class.

https://github.com/ngokchaoho/cantodict-kindle-mobi
